### ISSUE TITLE
Python library

### ISSUE THREAD

**Issue by Aryan-Deshpande** [sharat87/httpbun#1]
If there was a Python library built for the same, to test the flask applications that would be awesome.

**Comment by sharat87** [comment]
Hey @Aryan-Deshpande, thank you for your interest in this project. I'm not sure I understand your question though. Do you mean like a Python library that runs an instance of httpbun for testing? Httpbun is itself written in Golang, so exporting it as a Python library is a little non-straightforward.

**Comment by sharat87** [comment]
Closing this since there's few details for me to even understand what's being requested here. If there's more details in the future, happy to reopen. Thanks!
