### ISSUE TITLE
`503` returns `504`

### ISSUE THREAD

**Issue by AlexV525** [sharat87/httpbun#14]
https://httpbun.com/status/503

- https://github.com/cfug/dio/actions/runs/7069545281/job/19246540081?pr=2049

**Comment by sharat87** [comment]
Hey @AlexV525, thanks for reporting. Looks like DigitalOcean Apps platform is changing the status to `504` and saving the actual status in the `x-do-orig-status` header.

I've moved the deployment to DO earlier today to cope with [traffic from HN](https://news.ycombinator.com/item?id=38497519), looks like it had more unintended consequences. I intend to revert to the previous deployment within the next 12h and this error should be gone.

Slightly tangentially, please consider running the `httpbun` container in the workflow locally, and using that for tests. I'm unfortunately not in a position to promise an SLA for httpbun.com's uptime. Less reliance on third party URLs' uptime should also make the CI more resilient either way.

**Comment by AlexV525** [comment]
Thanks for the rapid response @sharat87

Unfortunately we did try to deploy a local version before, but our integrations involve SSL tests that failed to setup before and we didn't manage to figure it out (tho it maybe outdated). We'll try again when we're free from other tasks. Meanwhile, if you would like to, we are honored to have you help us improve the CI setup, that would be awesome.

I'll ignore the issue until you fix it.

**Comment by sharat87** [comment]
I see. If I'm getting this right, you want to hit httpbun with SSL, and that's not as straightforward when run locally, right? We've actually solved that problem recently by generating certs with `mkcert`, doing `mkcert -install` and using that to run local dependency containers that need SSL.

Let me see if I can get something up. (Not right now, unfortunately, I'll need some time). 🙂

**Comment by AlexV525** [comment]
> I see. If I'm getting this right, you want to hit httpbun with SSL, and that's not as straightforward when run locally, right? 

We have tests with SSL-pinning, Bad SSL, etc.

**Comment by sharat87** [comment]
This is fixed now.

**Comment by sharat87** [comment]
@AlexV525, I managed to get a local httpbun running with TLS at `https://httpbun.local` on CI. Here's a run: https://github.com/sharat87/dio-for-httpbun/actions/runs/7075989755/job/19258728233. Screenshot since GitHub will delete those logs in a few days:

![shot-2023-12-03-09-36-18](https://github.com/sharat87/httpbun/assets/120119/f4ecdb5a-aee5-45e4-b594-6a838eab99ee)

Workflow step that does this:

```yaml
      - name: Start local httpbun
        run: |
          mkcert -install
          mkcert -cert-file '/tmp/cert.pem' -key-file '/tmp/key.pem' httpbun.local
          echo '127.0.0.1 httpbun.local' | sudo tee --append /etc/hosts
          docker run \
            --name httpbun \
            --detach \
            --publish 443:443 \
            --volume /tmp:/tmp:ro \
            --env HTTPBUN_TLS_CERT=/tmp/cert.pem \
            --env HTTPBUN_TLS_KEY=/tmp/key.pem \
            --pull always \
            sharat87/httpbun
          sleep 1
          curl --fail --silent --show-error https://httpbun.local/any
```

However, as you can see, the tests fail for I think cert verification error. In the output of `mkcert -install`, we see this:

```
The local CA is now installed in the system trust store! ⚡️
ERROR: no Firefox and/or Chrome/Chromium security databases found
The local CA is already installed in Java's trust store! 👍
```

And yet, we're running the tests on Chrome and Firefox, from what I understand. Are we installing Chrome and Firefox later on? I'm thinking the missing piece here is to get Chrome/Firefox to trust `mkcert`'s CA and it should start working.

**Comment by AlexV525** [comment]
Thanks @sharat87
Could you setup a pull request so I can make modifications?

**Comment by sharat87** [comment]
@AlexV525, of course 🤦. Just opened one at https://github.com/cfug/dio/pull/2051.
