### ISSUE TITLE
/status endpoint does not respect Accept: */* header

### ISSUE THREAD

**Issue by dhudec** [sharat87/httpbun#21]
It is common for http clients to default to sending an `Accept: */*` header on requests, e.g. Postman defaults to using this header on all requests unless overridden. 

When a `/status/*` request is sent with `Accept: */*`, httpbun responds with an empty response, which caused me some confusion, especially given that  passing a more specific header of `Accept: application/json` or `Accept: text/plain` does return a response body. This is due to the explicit `Accept` header matching logic [here](https://github.com/sharat87/httpbun/blob/5025308c3a9df224c10faae403ae888ad5c3ecc5/routes/routes.go#L138). 

It may be more intuitive for users to support wildcard `Accept` headers, either by returning `application/json` or `text/plain` content by default when `Accept: */*` is received.

**Comment by sharat87** [comment]
Hey @dhudec, thanks for reporting with such detail. Appreciate the effort put in. 🙏

This logic was deliberately added to maintain compatibility with `httpbin`, which doesn't include _any_ response body for `/status` at all. But I wanted some body content for some of my tests, so added that explicit behaviour, when a specific `Accept` is given.

I'd actually like to respond with `application/json` when there's `Accept: */*` or when there's no `Accept` header, for consistency with all the other endpoints. But that would mean one more endpoint that behaves differently from httpbin.

Come to think of it, I think trying to maintain compatibility with httpbin is a lost cause, with little value now. It felt a lot more important back when I wrote that code.

Oh well. How about this? If we see `Accept: text/plain`, we respond with `text/plain`, else we respond with `application/json`, irrespective of everything else. What say?

**Comment by dhudec** [comment]
> If we see Accept: text/plain, we respond with text/plain, else we respond with application/json, irrespective of everything else. What say?

That sounds like a good solution 👍
