### ISSUE TITLE
Empty /status/ pages

### ISSUE THREAD

**Issue by adbar** [sharat87/httpbun#3]
Hi @sharat87, thanks for the alternative to httpbin! I now use it as the original website is not as reliable as it was.

Switching between both platforms is easy, the `/status/` pages however function differently: since it's about the HTTP code, could you please copy httpbin's behavior returning empty HTML documents?

Especially for redirects it makes little sense to display a web page, e.g. "301 Moved Permanently" for http://httpbun.org/status/301. An empty page would be better.

What do you think?

**Comment by sharat87** [comment]
Hey @adbar, thank you for the kind words.

This particular difference with httpbin was something I considered, and preferred this over just an empty response, that didn't convey anything, so was confusing. But I don't feel too strongly about this. If it helps with compatibility with httpbin, I think it's fine to change the behaviour here.

I won't be able to get to this until this weekend or early next week. Do you want to try contributing, if you need it sooner than that? 🙂

**Comment by adbar** [comment]
Hi @sharat87 Thanks for your prompt answer. I'm not that familiar with go and I can wait, so no worries.
