### ISSUE TITLE
/bytes/{count} should return bytes of a determined length.

### ISSUE THREAD

**Issue by tao12345666333** [sharat87/httpbun#4]
`/bytes/{count} ` will return an array containing a specific number of elements, rather than the length specified in the request.

https://github.com/sharat87/httpbun/blob/9654bbcf2233ac75bcda3ad41a63f591cb797bfb/util/util.go#LL36C1-L45C2

This will result in different **`content-length`** responses when accessing with the same parameters.

![2023-05-04 18-07-49屏幕截图](https://user-images.githubusercontent.com/3264292/236174834-db0881f2-e77a-43a3-841b-a4aa7acc170f.png)

**Comment by sharat87** [comment]
Hey @tao12345666333, thank you for reporting, this should be fixed now. 🙏
