### ISSUE TITLE
Image put/post returns no content

### ISSUE THREAD

**Issue by kuhnroyal** [sharat87/httpbun#5]
Thanks for this project and for providing this as service!

I am trying to move some code that used httpbin which puts/posts an `image/json`.
When trying this with httpbun I get a 200 response with content missing.
I would still expect to get a JSON response. httpbin returns a `data` field with `data:application/octet-stream;base64,DATA`.

Is that something that could be implemented?

**Comment by sharat87** [comment]
@kuhnroyal, thanks for raising this. Can you share a minimal `curl` command that uploads a JPEG and demonstrates this issue please? It'll help me ensure we're on the same page, and that I'm not out investigating some other non-issue. Thanks!

**Comment by sharat87** [comment]
Ahh okay, now that's an important piece of the puzzle. I've actually limited the incoming payload body size to 10000. I've originally done this to avoid having to deal with a single large incoming payload choking my resources, but looking at it now, it looks a little low.

Related code at https://github.com/sharat87/httpbun/blob/b7c19538ff81fb7fc055d74cf0ac170f0f195d5d/mux/mux.go#L60.

Can you confirm that if the payload is within 10kb, then things do work fine and as expected? 🤔
If yes, then the whole problem is with this explicit limit.

**Comment by kuhnroyal** [comment]
Well httbun returns 12288 as the highest content length I can reach by playing around in the CLI. But the difference is probably encoding related.

```json
"headers": {
    "Accept": "*/*",
    "Accept-Encoding": "deflate, gzip",
    "Connection": "close",
    "Content-Length": "12288",
    "Content-Type": "image/png",
    "User-Agent": "Dart/3.0 (dart:io)"
  }
```

I will try to use a smaller sample image in my tests and see how it goes.
Thanks!

**Comment by kuhnroyal** [comment]
Ok it consistently works with smaller samples. I am now just wondering if it would make more sense to return the binary data as Base64. I currently seem to be unable to compare it to the uploaded data.

**Comment by sharat87** [comment]
> I am now just wondering if it would make more sense to return the binary data as Base64. I currently seem to be unable to compare it to the uploaded data.

Good point. I'm a little hesitant of changing the behavior of the `data` field in the resulting JSON. So, perhaps add a `base64Data` field? But that would mean the uploaded image would show up >2x in the resulting JSON. Is that... okay? 🤔

**Comment by sharat87** [comment]
On another note, I just realized that we do respond with Base64, when using a multipart upload content type. For example,

```bash
curl -d @image.jpg https://httpbun.com/anything
```

This results in `data` field having the escaped binary of the payload image.

But if we do this:

```bash
curl -F image=@image.jpg https://httpbun.com/anything
```

This results in `data` field being empty, but the `files` field gets an `image` field, with the Base64 of the uploaded image.

I'm now thinking this is fine and expected. The best I think we can to improve the situation with raw file uploads (not multipart), is perhaps add the `base64Data` field, as described in the previous comment. Let me know if that sounds useful. I'm not fully decided on if we should add that.

**Comment by kuhnroyal** [comment]
Hmm multipart doesn't help, because I want to test the normal upload :)
What about a query flag to control the response format?

**Comment by sharat87** [comment]
> Hmm multipart doesn't help, because I want to test the normal upload :)

Fair enough. 🙂

>  What about a query flag to control the response format?

I'm wary of doing this, since query params are just included in the response JSON, with absolutely no special behaviour to them. I'd like to not add exceptions to that rule. (Rule being, no query param has any affect on the API's behaviour).

So, let me circle-back to the question here. We want to upload raw payload data, not as a multipart form request, and then get that binary payload back, encoded with Base64. Is this problem statement correct?

We already have a [`/payload`](https://httpbun.com#payload), which responds with the request payload verbatim, with the same `Content-Type`. So, if we add a similar `/payload-base64`, which would respond with the payload encoded with Base64, and `Content-Type` always being `text/plain`, ... that should solve for what you're looking for, right?

**Comment by kuhnroyal** [comment]
> So, let me circle-back to the question here. We want to upload raw payload data, not as a multipart form request, and then get that binary payload back, encoded with Base64. Is this problem statement correct?

Yes, but..
The only reason I want this, is because I have an old test which did it that way again httpbin and I can't figure out a way to compare the binary response content. I am uploading a PNG file and try to convert the response data field back to a png but it never matches.
I don't need Base64 if I can solve that.

Do you have a similar test somewhere?

**Comment by sharat87** [comment]
> I am uploading a PNG file and try to convert the response data field back to a png but it never matches.

Got it. I don't have a test for this yet, but let me look into this. This is a problem statement I can test and troubleshoot. I'll get back soon, depending on bandwidth. 🙂

**Comment by sharat87** [comment]
So, httpbin's behaviour is... just feels haphazard and incomplete. Check this out.

When I upload an image with the right image content-type, I don't get anything back.

```
> curl -d @image.jpg -H'content-type: image/jpeg' postman-echo.com/post
{
  "args": {},
  "data": {},
  "files": {},
  "form": {},
  "headers": {
    "x-forwarded-proto": "http",
    "x-forwarded-port": "80",
    "host": "postman-echo.com",
    "x-amzn-trace-id": "Root=1-6483f228-6e46d26d1c48dacd6bf60dc9",
    "content-length": "9022",
    "user-agent": "curl/7.88.1",
    "accept": "*/*",
    "content-type": "image/jpeg"
  },
  "json": null,
  "url": "http://postman-echo.com/post"
}
```

However, if I do it with `application/octet-stream`, the `data` field is an _object_!!!

```
> curl -d @$HOME/Pictures/profile.jpg -H'content-type: application/octet-stream' postman-echo.com/post
{
  "args": {},
  "data": {
    "type": "Buffer",
    "data": [
      255,
      216,
      ...
      184,
      244,
      168,
      80
    ]
  },
  "url": "http://postman-echo.com/post"
}
```

That `data.data` list contains all the byte numbers, I think. Very long list.

This is one way to do it, instead of base64. I'm a little split on which would be better here. Thoughts?

But the behavior for `image/jpeg` definitely seems odd. I'd expect it to do the same thing as `application/octet-stream`. 🤷

**Comment by kuhnroyal** [comment]
Yea the 2nd output makes a lot more sense and is probably enough to compare my sent data.

**Comment by sharat87** [comment]
Okay, even with `application/octet-stream`, postman-echo.com responds with the byte integer list, but httpbin.org (and pie.dev) respond with the base64 of the data. 🤷

But this also made the response size from postman-echo.com be ~13x that from httpbin.org. For example, 16Kb became 200Kb.

Considering this, I'm leaning towards base64. Also, from what I know, most languages come with standard utility functions to convert a base64 string to a byte-array (Python and Golang both do), and is usually more straightforward than converting a list of integers into a byte array.

I'm going to soon start with the base64 implementation, similar to how httpbin does it. Hope that's okay?

**Comment by kuhnroyal** [comment]
That would be great!

**Comment by kuhnroyal** [comment]
Thanks, confirmed working!
