### ISSUE TITLE
Support OPTIONS/CORS

### ISSUE THREAD

**Issue by kuhnroyal** [sharat87/httpbun#6]
I have CORS requests which fail with "405: Method not allowed" when sending the pre-flight OPTIONS request.
It seems the response access control headers are correct but the `OPTIONS` method is considered not allowed because it is the `put` endpoint.

I think all endpoints should allow `OPTIONS`. What do you think?

**Comment by sharat87** [comment]
Thanks @kuhnroyal for reporting this. Should be fixed now.

![shot-2023-05-31-02-33-41](https://github.com/sharat87/httpbun/assets/120119/37e4d02c-0404-46fb-a7e5-d7bfe3c34fcf)

**Comment by kuhnroyal** [comment]
Thanks, I can confirm that it works now!
