### ISSUE TITLE
Feature Request: endpoint to pull environment

### ISSUE THREAD

**Issue by Spazzy757** [sharat87/httpbun#7]
## Situation

It would be beneficial to have an endpoint that returns the containers environment as a JSON object

There is a use case for this in for instance testing multi-backend routing (like canary deployments or blue/green deployments), it would be good to know when hitting the backend things like the hostname and any other identifying information that can be injected into the container to understand different patterns

**Comment by Spazzy757** [comment]
I had some time, feel free to close the PR if you are not happy with it :smile:

**Comment by sharat87** [comment]
Hey @Spazzy757, ensuring that I understand your use case, can you share how you're running Httpbun? Like, do you have multiple containers of Httpbun, as part of a larger `docker-compose.yml` file? If yes, can you give a minimal sample of this please? I'm just trying to understand the problem better, before I start to have an opinion on the proposed solution. 🙂

Thanks for reaching out, by the way. 🍻

**Comment by Spazzy757** [comment]
Hi!

Yes we are currently using it in in Ingress Nginx for E2E testing as well as for our examples, there are some places we use echo server but I would like to migrate over to http un but we use echo with some env variables 

https://github.com/kubernetes/ingress-nginx

**Comment by Spazzy757** [comment]
I can get some examples for you on Monday

**Comment by sharat87** [comment]
Oh okay, got it. We already have a `/info` endpoint that returns the hostname of the container like this:
https://github.com/sharat87/httpbun/blob/c07406ab38f055691b5cc18ee0f5b7e0dbdc9a0e/bun/bun.go#L490-L499

But this is disabled by default.
https://github.com/sharat87/httpbun/blob/c07406ab38f055691b5cc18ee0f5b7e0dbdc9a0e/bun/bun.go#L97-L99

Would this solve this problem of identifying the source of the response? If not, we can add the `env` map to this endpoint itself, and, make it enabled by default. I'm not sure why I disabled this endpoint by default. 🤷

**Comment by Spazzy757** [comment]
I think there are cases when we need things like the POD IP (https://kubernetes.github.io/ingress-nginx/examples/canary/) I did like the info endpoint, but felt it was missing some other networking info. For instance, we do some hackery where we are using multiple services with the same name across different namespaces, this makes the hostname useless as they will all be something like `canary-xxxx` but the IP address information will be unique and we need to validate we are hitting the correct IP address. I would be happy if you added some more info to the `/info` endpoint but even then it makes it a bit difficult for instance when we want to know the namespace of the pod we are routing to (we can inject this as part of the environment without to many issues) and maybe some other edge case information (i.e what node the pod is running on).

**Comment by sharat87** [comment]
Hey, sorry for the delay. Yes, that makes a lot much more sense now. Let's add env variables. But, instead of `/env`, let's add a `"env"` field in the response of `/info` itself? Like:

```
{
  "hostname": "httpbun-pod-0",
  "env": {
    "COLOR": "red"
  }
```

Would that work? What say? If yes, would can you make this API change in your PR please?
