### ISSUE TITLE
Provide an linux/arm64/v8 build

### ISSUE THREAD

**Issue by trajano** [sharat87/httpbun#9]
You can take a look here https://github.com/trajano/trajano-portfolio/blob/43549b78fad9fc94f98fffe94a7964c39f28b65e/.github/workflows/publish.yml#L74-L82

But basically if you add this platforms: linux/amd64,linux/arm64,linux/arm/v7 you'd provide good enough coverage for most environments.

**Comment by sharat87** [comment]
Oh hey @trajano, thanks for opening this. I didn't prioritize this as I didn't need it, and was waiting to see if someone would ask, to justify prioritizing it.

This is all I need. I'll get this done this weekend or early next week.

**Comment by sharat87** [comment]
This is now available. Thank you.

![shot-2023-09-02-04-14-21](https://github.com/sharat87/httpbun/assets/120119/c8a13dd1-d747-4750-b049-0cda7fcd7600)

**Comment by trajano** [comment]
Thanks for your patience. It works on my pi [trajano.net/httpbin/get](https://trajano.net/httpbin/get)
